/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author zeyn
 */
public class Calculator extends javax.swing.JFrame {

    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yaziyeri = new javax.swing.JTextField();
        artieksi = new javax.swing.JButton();
        solaok = new javax.swing.JButton();
        ceyazi = new javax.swing.JButton();
        cyazi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        yedisayi = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        nokta = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yaziyeri.setFont(new java.awt.Font("Sitka Text", 0, 33)); // NOI18N
        yaziyeri.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yaziyeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaziyeriActionPerformed(evt);
            }
        });
        getContentPane().add(yaziyeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 490, 60));

        artieksi.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        artieksi.setForeground(new java.awt.Color(0, 0, 255));
        artieksi.setText("±");
        artieksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artieksiActionPerformed(evt);
            }
        });
        getContentPane().add(artieksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 190, 80));

        solaok.setBackground(new java.awt.Color(204, 0, 0));
        solaok.setFont(new java.awt.Font("Cascadia Mono", 1, 36)); // NOI18N
        solaok.setForeground(new java.awt.Color(255, 255, 255));
        solaok.setText("←");
        solaok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solaokActionPerformed(evt);
            }
        });
        getContentPane().add(solaok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 80));

        ceyazi.setBackground(new java.awt.Color(0, 51, 255));
        ceyazi.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        ceyazi.setForeground(new java.awt.Color(255, 255, 255));
        ceyazi.setText("Ce");
        ceyazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceyaziActionPerformed(evt);
            }
        });
        getContentPane().add(ceyazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 80));

        cyazi.setBackground(new java.awt.Color(0, 51, 255));
        cyazi.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        cyazi.setForeground(new java.awt.Color(255, 255, 255));
        cyazi.setText("C");
        cyazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyaziActionPerformed(evt);
            }
        });
        getContentPane().add(cyazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 80));

        jButton5.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 90, 170));

        yedisayi.setBackground(new java.awt.Color(51, 204, 255));
        yedisayi.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        yedisayi.setForeground(new java.awt.Color(255, 255, 255));
        yedisayi.setText("7");
        yedisayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yedisayiActionPerformed(evt);
            }
        });
        getContentPane().add(yedisayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 80));

        jButton7.setBackground(new java.awt.Color(51, 204, 255));
        jButton7.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("8");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 80));

        jButton8.setBackground(new java.awt.Color(51, 204, 255));
        jButton8.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("9");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, 80));

        jButton13.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 255));
        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 90, 80));

        jButton14.setBackground(new java.awt.Color(51, 204, 255));
        jButton14.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("4");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 80));

        jButton15.setBackground(new java.awt.Color(51, 204, 255));
        jButton15.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("5");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 80));

        jButton16.setBackground(new java.awt.Color(51, 204, 255));
        jButton16.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("6");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 90, 80));

        jButton17.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 255));
        jButton17.setText("x");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 90, 80));

        jButton18.setBackground(new java.awt.Color(51, 204, 255));
        jButton18.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("1");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 80));

        jButton19.setBackground(new java.awt.Color(51, 204, 255));
        jButton19.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("2");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 90, 80));

        jButton20.setBackground(new java.awt.Color(51, 204, 255));
        jButton20.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("3");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 90, 80));

        jButton21.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 0, 255));
        jButton21.setText("%");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 80));

        jButton22.setBackground(new java.awt.Color(0, 102, 204));
        jButton22.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("000");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 90, 80));

        nokta.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        nokta.setForeground(new java.awt.Color(0, 0, 255));
        nokta.setText(".");
        nokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaActionPerformed(evt);
            }
        });
        getContentPane().add(nokta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 90, 80));

        jButton24.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton24.setForeground(new java.awt.Color(0, 0, 255));
        jButton24.setText("=");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 90, 170));

        jButton23.setBackground(new java.awt.Color(0, 102, 204));
        jButton23.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("0");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 80));

        jButton25.setBackground(new java.awt.Color(0, 102, 204));
        jButton25.setFont(new java.awt.Font("Stencil", 1, 33)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("00");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers (String q)
    {
        String Nums = yaziyeri.getText() + q;
        yaziyeri.setText(Nums);
    }
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void yedisayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yedisayiActionPerformed

        EnterNumbers("7");
    }//GEN-LAST:event_yedisayiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       EnterNumbers("8");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        EnterNumbers("000");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        NumEnter1 = Double.parseDouble(yaziyeri.getText());
        yaziyeri.setText("");
        op= "/";
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        NumEnter1 = Double.parseDouble(yaziyeri.getText());
        yaziyeri.setText("");
        op= "*";
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        NumEnter1 = Double.parseDouble(yaziyeri.getText());
        yaziyeri.setText("");
        op= "-";
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        NumEnter1 = Double.parseDouble(yaziyeri.getText());
        yaziyeri.setText("");
        op= "+";
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ceyaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceyaziActionPerformed
        yaziyeri.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_ceyaziActionPerformed

    private void cyaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyaziActionPerformed
        yaziyeri.setText("");
    }//GEN-LAST:event_cyaziActionPerformed

    private void artieksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artieksiActionPerformed
        
        double nums = Double.parseDouble(String.valueOf(yaziyeri.getText()));
        
        nums= nums*(-1);
        yaziyeri.setText(String.valueOf ( nums));
    }//GEN-LAST:event_artieksiActionPerformed

    private void solaokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solaokActionPerformed
        
        String backSp = null;
        
        if(yaziyeri.getText().length() > 0) 
        {
           StringBuilder sb = new StringBuilder(yaziyeri.getText());
           sb.deleteCharAt(yaziyeri.getText().length() - 1);
           backSp = sb.toString();
           yaziyeri.setText(backSp);
            
        }
    }//GEN-LAST:event_solaokActionPerformed

    private void yaziyeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaziyeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaziyeriActionPerformed

    private void noktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaActionPerformed
        
        if(! yaziyeri.getText(). contains(".") )
        {
           yaziyeri.setText(yaziyeri.getText() + nokta.getText());
             
        }
    }//GEN-LAST:event_noktaActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        EnterNumbers("00");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        EnterNumbers("9");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

        NumEnter2 = Double.parseDouble(yaziyeri.getText());
        if (op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            yaziyeri.setText(String.valueOf(Result));
        }

        else  if (op == "-")
        {
            Result = NumEnter1 - NumEnter2;
            yaziyeri.setText(String.valueOf(Result));
        }

        else if (op == "/")
        {
            Result = NumEnter1 / NumEnter2;
            yaziyeri.setText(String.valueOf(Result));
        }

        else  if (op == "*")
        {
            Result = NumEnter1 * NumEnter2;
            yaziyeri.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton artieksi;
    private javax.swing.JButton ceyazi;
    private javax.swing.JButton cyazi;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton nokta;
    private javax.swing.JButton solaok;
    private javax.swing.JTextField yaziyeri;
    private javax.swing.JButton yedisayi;
    // End of variables declaration//GEN-END:variables
}

